-- F16 Arena — этап 3: Server Agent, инстансы CS2, события MatchZy, статистика по картам.

-- id матча для MatchZy (MatchZy принимает только целое число)
alter table matches add column matchzy_id bigint generated by default as identity unique;
alter table matches add column server_instance text;
alter table matches add column server_state text check (server_state in ('assigned', 'loading', 'ready', 'error'));

-- ───────────────────────── хост и инстансы (заполняет агент)
create table server_host (
  id           text primary key default 'main',
  lan_ip       text,
  last_seen_at timestamptz,
  info         jsonb not null default '{}'::jsonb   -- cpu, ram, disk, build, версии плагинов
);

create table server_instances (
  name             text primary key,                 -- CS2-01
  port             int  not null,
  role             text not null default 'active' check (role in ('active', 'reserve')),
  running          boolean not null default false,
  gamestate        text,                              -- из get5_status: none / warmup / knife / live / post_game …
  map              text,
  players          int,
  matchzy_match_id bigint,
  match_id         uuid references matches(id) on delete set null,
  last_seen_at     timestamptz,
  info             jsonb not null default '{}'::jsonb
);

insert into server_instances (name, port, role) values
  ('CS2-01', 27015, 'active'),
  ('CS2-02', 27115, 'active'),
  ('CS2-03', 27215, 'active'),
  ('CS2-04', 27315, 'reserve'),
  ('CS2-05', 27415, 'reserve');

alter table matches add constraint matches_server_instance_fkey
  foreign key (server_instance) references server_instances(name) on delete set null;

-- ───────────────────────── очередь команд агенту
create table agent_commands (
  id         uuid primary key default gen_random_uuid(),
  instance   text references server_instances(name),
  type       text not null,          -- start / stop / restart / load_match / end_match / rcon
  payload    jsonb not null default '{}'::jsonb,
  status     text not null default 'pending' check (status in ('pending', 'sent', 'done', 'error')),
  result     text,
  created_by uuid references players(id),
  created_at timestamptz not null default now(),
  sent_at    timestamptz,
  done_at    timestamptz
);
create index agent_commands_pending on agent_commands(created_at) where status = 'pending';

-- ───────────────────────── сырые события MatchZy (для пересчёта статистики и MVP)
create table match_events (
  id           bigint generated always as identity primary key,
  match_id     uuid references matches(id) on delete cascade,
  matchzy_id   bigint,
  event        text not null,
  map_number   int,
  round_number int,
  payload      jsonb not null,
  received_at  timestamptz not null default now()
);
create index match_events_match on match_events(match_id, id);

-- ───────────────────────── статистика игрока за карту (накопительная, из round_end / map_result)
create table player_map_stats (
  match_id       uuid not null references matches(id) on delete cascade,
  map_number     int  not null,
  steam_id       text not null,
  player_id      uuid references players(id),
  team_id        uuid references teams(id),
  name           text,
  kills          int not null default 0,
  deaths         int not null default 0,
  assists        int not null default 0,
  damage         int not null default 0,
  headshot_kills int not null default 0,
  rounds_played  int not null default 0,
  kast           int not null default 0,   -- раундов с KAST
  first_kills    int not null default 0,
  first_deaths   int not null default 0,
  trade_kills    int not null default 0,
  clutch_wins    int not null default 0,   -- сумма 1v1..1v5
  multi_kills    jsonb not null default '{}'::jsonb,  -- {"2k":..,"3k":..,"4k":..,"5k":..}
  utility_damage int not null default 0,
  enemies_flashed int not null default 0,
  flash_assists  int not null default 0,
  bomb_plants    int not null default 0,
  bomb_defuses   int not null default 0,
  mvp            int not null default 0,
  raw            jsonb not null default '{}'::jsonb,
  updated_at     timestamptz not null default now(),
  primary key (match_id, map_number, steam_id)
);

alter table server_host      enable row level security;
alter table server_instances enable row level security;
alter table agent_commands   enable row level security;
alter table match_events     enable row level security;
alter table player_map_stats enable row level security;
create policy "public read" on player_map_stats for select using (true);
